# Making a 3D Dimension Array :

In [83]:
#Load Library
import numpy as np

In [84]:
A = np.arange(12).reshape(2,3,2)

This will give you a 3-dimensional NumPy array with:
- 2 blocks (or arrays),
- each containing 3 rows,
- and each row containing 2 columns.


In [85]:
A

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In NumPy, arrays are zero-indexed — meaning:
- Block 1 → A[0]
- Block 2 → A[1]
- Row 1 → 0
- Column 1 → 0

## Selecting One or more Elements

In [86]:
#Select 1st Element
A[0]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [87]:
#Select 2nd row and 2nd column
A[1,1]

array([8, 9])

## To Access and print the element in block : 2 , Row : 1,Column : 1

In [88]:
A[0,1,1]

np.int64(3)

Like Most of the things in Python NumPy arrays are Zero indexed .
means the Index of first elementis 0 ,not 1.
NumPy's has a variety of Methods for selecting (indexing and slicing)

In [89]:
array = np.arange(10)

In [90]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
#Select every thing upto 3
array[:3]

array([0, 1, 2])

In [92]:
#Select everything after 3
array[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [93]:
#Select the Last Element
array[-1]

np.int64(9)

In [94]:
#Reverse the Array
array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [95]:
#Select the First 2 rows and all the Colomns
A[:2,:]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [96]:
#Select all rows and 2nd Column
A[:,1:2]

array([[[2, 3]],

       [[8, 9]]])

##Print only the Last Row

In [119]:
#Print only last row
A[-1,-1]

array([10, 11])

In [122]:
#Print Last Row of every block
last_row = A[:,-1:]
print("Last Row of Every Block: ")
print(last_row)

Last Row of Every Block: 
[[[ 4  5]]

 [[10 11]]]


## Reverse the order of the blocks in the array.

In [97]:
A[::-1]

array([[[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])

## Describe a shape ,Size and Dimensions :

In [98]:
#View no. of Row and Columns
A.shape

(2, 3, 2)

In [99]:
#View no. of elements (rows * Columns)
A.size

12

In [100]:
#view no.of Dimensions
A.ndim

3

# Find Minimum

In [101]:
np.min(A)


np.int64(0)

# Find Maximum

In [102]:
np.max(A)


np.int64(11)

In [103]:
#Print the Max Value in each 2D block
for i in range(A.shape[0]):
  block_max = np.max(A[i])
  print(f" Max value in block {i + 1} : {block_max}")

 Max value in block 1 : 5
 Max value in block 2 : 11


## Caculating  the Average, Variance ,and Standard Deviation.
 Use NumPy's mean, var ,std

In [104]:
#Return Mean
np.mean(A)

np.float64(5.5)

In [105]:
#Return variance
np.var(A)


np.float64(11.916666666666666)

In [106]:
#return standard deviation
np.std(A)

np.float64(3.452052529534663)

You could Apply Functions to an Array or Simply just add 100 .

# Add 100 to the Array

In [107]:
#add 100 to all Element
A + 100


array([[[100, 101],
        [102, 103],
        [104, 105]],

       [[106, 107],
        [108, 109],
        [110, 111]]])

# Loop through all blocks and print the sum of each block.


In [114]:
#load Library
import numpy as np


In [115]:
#create Array
Ar = np.arange(12).reshape(2,3,2)

In [116]:
for i in range(Ar.shape[0]):
   block_sum = Ar[i].sum()
   print(f"Sum of Block {i + 1}:{ block_sum }")

Sum of Block 1:15
Sum of Block 2:51


##Convert the 3D array into a 1D array (flatten it).




In [117]:
#Flatten an 3D
Ar.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Replace all even numbers in the array with 0.


In [125]:
A[A % 2 == 0] = 0

In [127]:
print("Modified Array with even numbers replaced with 0:  ")
print(A)

Modified Array with even numbers replaced with 0:  
[[[ 0  1]
  [ 0  3]
  [ 0  5]]

 [[ 0  7]
  [ 0  9]
  [ 0 11]]]


## Count how many numbers in the array are greater than 10.

In [129]:
count = np.sum(Ar > 10)
print(f"Number of elements greater than 10: {count}")

Number of elements greater than 10: 1
